Rails.application.routes.draw do
  # The commented code is generated by 'rails g controller' command.
  # and is being replaced by the following routes.
  #get 'users/new'

  root            'static_pages#home'  

  get 'help'   => 'static_pages#help'
  get 'about'  => 'static_pages#about'
  get 'signup' => 'users#new'

  resources :users
end
