Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  # The commented code is generated by 'rails g controller' command.
  # and is being replaced by the following routes.
  #get 'users/new'

  root               'static_pages#home'  

  get    'help'   => 'static_pages#help'
  get    'about'  => 'static_pages#about'
  get    'signup' => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]

end
